server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: school-management-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/school_management
    username: postgres
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USER:}
    password: ${EMAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your_super_secret_jwt_key_here_make_it_long_and_random}
  expiration: ${JWT_EXPIRES_IN:604800000} # 7 days in milliseconds

# Razorpay Configuration
razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_xxx}
  key-secret: ${RAZORPAY_KEY_SECRET:xxx}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:xxx}

# File Upload Configuration
file:
  upload-dir: ${UPLOAD_PATH:./uploads}

# School Configuration
school:
  name: ${SCHOOL_NAME:Your School Name}
  address: ${SCHOOL_ADDRESS:Your School Address}
  phone: ${SCHOOL_PHONE:Your School Phone}
  email: ${SCHOOL_EMAIL:your_school@email.com}

# Logging
logging:
  level:
    com.schoolms: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
